# Generated by Django 2.2 on 2021-03-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='hodnota_atributu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attrstovalue', to='core.AttributeValue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mena',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
